apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: mysql-image:latest
      imagePullPolicy: IfNotPresent
      readinessProbe:
        tcpSocket:
          port: 3306 # MySQL port
        initialDelaySeconds: 10 # Wait 10 seconds before the first probe
        periodSeconds: 10     # Check every 10 seconds
      env:
        - name: MYSQL_DATABASE
          value: database
        - name: MYSQL_USER
          value: admin
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
