apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
spec:
  containers:
    - name: webserver-container
      image: webserver-image:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
