version: '3'
services:

  webserver:
    build:
      context: ./webserver/
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - "./webserver/website:/var/www/html"
    depends_on:
      - mysql
    
  mysql:
    image: mysql:latest
    build:
      context: ./mysql/
      dockerfile: Dockerfile
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./mysql:/docker-entrypoint-initdb.d"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306